services:
  - name: maxine-main-api
    type: web
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    buildCommand: "docker build -t my-laravel-app ."
    startCommand: "docker run -d -p 80:80 my-laravel-app"